import { StyleSheet, Dimensions } from "react-native";
const vw = Dimensions.get("window").width,
  vh = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  heading: {
    color: "#fff",
    fontSize: 25,
    top: vh * 0.04,
    width: vw * 0.6,
    left: 0.2 * vw,
    textAlign: "center",
    position: "absolute",
  },
  errorText: { top: 0, color: "red", fontSize: 18, textAlign: "center" },
  container: {
    width: vw,
    height: vh,
    position: "absolute",
    zIndex: 4,
    top: 0,
    left: 0,
  },
  form: {
    top: vh * 0.1,
    alignSelf: "stretch",
    height: vh * 0.87,
  },
  textInput: {
    color: "#fff",
    borderColor: "#11191C",
    borderBottomColor: "gray",
    borderWidth: 1,
    marginBottom: 30,
    borderRadius: 2,
    padding: 5,
    width: "70%",
    alignSelf: "center",
  },
  dropdownPicker: {
    borderColor: "#11191C",
    borderBottomColor: "gray",
    borderWidth: 1,
    width: "70%",
    alignSelf: "center",
    marginBottom: 20,
  },
  selectAdButton: {
    backgroundColor: "#52b788",
    borderRadius: 10,
    width: "80%",
    textAlign: "center",
    textAlignVertical: "center",
    height: 40,
    alignSelf: "center",
    fontSize: 25,
    color: "black",
  },
  uploadButton: {
    backgroundColor: "dodgerblue",
    borderRadius: 10,
    width: "100%",
    bottom: 0,
    textAlign: "center",
    position: "absolute",
    height: 45,
    textAlignVertical: "center",
    fontSize: 25,
    color: "black",
  },
});
