export const DRAWER_STATE = "DRAWER_STATE";
export const REGISTRATION = "REGISTRATION";
export const INIT_STATE_STORAGE = "INIT_STATE_STORAGE";
export const BLUETOOTH_DATA = "BLUETOOTH_DATA";
export const ANALYTICS_DATA = "ANALYTICS_DATA";
